Fix android_run_skia to work with multiple attached devices
(SkipBuildbotRuns)

R=djsollen@google.com

Review URL: https://codereview.chromium.org/15199005

git-svn-id: http://skia.googlecode.com/svn/trunk@9167 2bbb7eff-a529-9590-31e7-b0007b416f81

diff --git a/platform_tools/android/bin/android_kill_skia b/platform_tools/android/bin/android_kill_skia
--- a/platform_tools/android/bin/android_kill_skia
+++ b/platform_tools/android/bin/android_kill_skia
@@ -6,10 +6,27 @@ SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 source $SCRIPT_DIR/utils/setup_adb.sh
 
+SERIAL=""
+
+while (( "$#" )); do
+
+  if [[ "$1" == "-s" ]];
+  then
+    if [[ $# -lt 2 ]];
+    then
+      echo "ERROR: missing serial number"
+      exit 1;
+    fi
+    SERIAL="-s $2"
+    shift
+  fi
+  shift
+done
+
 if [ $(uname) == "Linux" ]; then
-    $ADB shell ps | grep skia | awk '{print $2}' | xargs -r $ADB shell kill
+    $ADB $SERIAL shell ps | grep skia | awk '{print $2}' | xargs -r $ADB $SERIAL shell kill
 elif [ $(uname) == "Darwin" ]; then
-    $ADB shell ps | grep skia | awk '{print $2}' | xargs $ADB shell kill
+    $ADB $SERIAL shell ps | grep skia | awk '{print $2}' | xargs $ADB $SERIAL shell kill
 else
     echo "Could not automatically determine OS!"
     exit 1;
