Update Skia Android tools.
This CL moves the skia_launcher out of the system/bin and into
/data/local/tmp; removes the need to package our shared libs in an
apk; and updates all the scripts to work in the new environment.

R=mtklein@google.com, scroggo@google.com

Review URL: https://codereview.chromium.org/22617002

git-svn-id: http://skia.googlecode.com/svn/trunk@10673 2bbb7eff-a529-9590-31e7-b0007b416f81

diff --git a/platform_tools/android/bin/android_gdbserver b/platform_tools/android/bin/android_gdbserver
--- a/platform_tools/android/bin/android_gdbserver
+++ b/platform_tools/android/bin/android_gdbserver
@@ -4,49 +4,57 @@
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 source $SCRIPT_DIR/android_setup.sh
+source $SCRIPT_DIR/utils/setup_adb.sh
 
-APP_NAME=${APP_ARGS[0]}
+configuration="Debug"
+
+for arg in ${APP_ARGS[@]}
+do
+  if [[ "${arg}" == "--release" ]];
+  then 
+    configuration="Release"
+  else
+    gdbVars=("${gdbVars[@]}" "${arg}")
+  fi
+
+shift
+done
+
+APP_NAME=${gdbVars[0]}
 PORT=5039
 
-source $SCRIPT_DIR/utils/setup_adb.sh
+if [ ! -f "${SKIA_OUT}/${configuration}/lib.target/lib${gdbVars[0]}.so" ];
+then
+  echo "Unable to find the ${gdbVars[0]} library"
+  exit 1
+fi
 
 # We need the debug symbols from these files
 GDB_TMP_DIR=$(pwd)/android_gdb_tmp
 mkdir $GDB_TMP_DIR
+
 echo "Copying symbol files"
-adb_pull_if_needed /system/bin/skia_launcher $GDB_TMP_DIR
 adb_pull_if_needed /system/lib/libc.so $GDB_TMP_DIR
-adb_pull_if_needed /data/data/com.skia/lib/libskia_android.so $GDB_TMP_DIR
-adb_pull_if_needed /data/data/com.skia/lib/lib$APP_NAME.so $GDB_TMP_DIR
+cp "${SKIA_OUT}/${configuration}/skia_launcher" $GDB_TMP_DIR
+cp "${SKIA_OUT}/${configuration}/lib.target/libskia_android.so" $GDB_TMP_DIR
+cp "${SKIA_OUT}/${configuration}/lib.target/lib${APP_NAME}.so" $GDB_TMP_DIR
 
-echo "Checking for skia_launcher app..."
-if [ ! -f $GDB_TMP_DIR/skia_launcher ]
-then
-    echo "Unable for find the skia_launcher on the device"
-    rm -rf $GDB_TMP_DIR
-    exit 1;
-fi
-
-echo "Checking for $APP_NAME library..."
-if [ ! -f $GDB_TMP_DIR/lib$APP_NAME.so ]
-then
-    echo "Unable for find the app's shared library on the device"
-    rm -rf $GDB_TMP_DIR
-    exit 1;
-fi
+echo "Pushing app..."
+adb_push_if_needed "${SKIA_OUT}/${configuration}/skia_launcher" /data/local/tmp
+adb_push_if_needed "${SKIA_OUT}/${configuration}/lib.target/libskia_android.so" /data/local/tmp
+adb_push_if_needed "${SKIA_OUT}/${configuration}/lib.target/lib${APP_NAME}.so" /data/local/tmp
 
 echo "Pushing gdbserver..."
-$ADB remount
-$ADB push $ANDROID_TOOLCHAIN/../gdbserver /system/bin/gdbserver
+adb_push_if_needed $ANDROID_TOOLCHAIN/../gdbserver data/local/tmp
 
 echo "Setting up port forward"
 $ADB forward "tcp:5039" "tcp:5039"
 
-# Kill all previous instances of gdbserver and skia_launcher to rid all port overriding errors.
+# Kill all previous instances of gdbserver and the app to rid all port overriding errors.
 echo "Killing any running Skia processes."
 $ADB shell ps | grep gdbserver | awk '{print $2}' | xargs $ADB shell kill
-$ADB shell ps | grep skia_launcher | awk '{print $2}' | xargs $ADB shell kill
+$ADB shell ps | grep ${APP_NAME} | awk '{print $2}' | xargs $ADB shell kill
 
 # Starting up gdbserver in android shell
-echo "Starting gdbserver with command: skia_launcher $APP_ARGS"
-$ADB shell gdbserver :5039 /system/bin/skia_launcher $APP_ARGS & 
+echo "Starting gdbserver with command: ${gdbVars[@]}"
+$ADB shell /data/local/tmp/gdbserver :5039 /data/local/tmp/skia_launcher ${gdbVars[@]} & 
diff --git a/platform_tools/android/bin/android_perf b/platform_tools/android/bin/android_perf
--- a/platform_tools/android/bin/android_perf
+++ b/platform_tools/android/bin/android_perf
@@ -9,8 +9,7 @@
 #
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-PERF_CMD=$1
-
+source $SCRIPT_DIR/android_setup.sh
 source $SCRIPT_DIR/utils/setup_adb.sh
 
 if [ $(uname) == "Linux" ]; then
@@ -22,77 +21,70 @@ else
     exit 1;
 fi
 
+# grab and remove the perf command from the input args
+PERF_CMD=${APP_ARGS[0]}
+unset APP_ARGS[0]
+
+configuration="Debug"
+
+for arg in ${APP_ARGS[@]}
+do
+  if [[ "${arg}" == "--release" ]];
+  then 
+    configuration="Release"
+  else
+    echo "${arg}"
+    runVars=("${runVars[@]}" "${arg}")
+  fi
+
+shift
+done
+
 # We need the debug symbols from these files
 PERF_TMP_DIR=$(pwd)/android_perf_tmp
 
 TMP_SYS_BIN=$PERF_TMP_DIR/system/bin
 TMP_SYS_LIB=$PERF_TMP_DIR/system/lib
-TMP_APP_LIB=$PERF_TMP_DIR/data/data/com.skia/lib
+TMP_APP_LOC=$PERF_TMP_DIR/data/local/tmp
 
 perf_setup() {
 
     mkdir -p $TMP_SYS_BIN
     mkdir -p $TMP_SYS_LIB
-    mkdir -p $TMP_APP_LIB
+    mkdir -p $TMP_APP_LOC
 
-    # setup symlinks to account for perf potentially looking elsewhere
-    mkdir -p $PERF_TMP_DIR/data/app-lib
-    $( cd $PERF_TMP_DIR/data/app-lib && ln -s ../data/com.skia/lib com.skia-1)
-    $( cd $PERF_TMP_DIR/data/app-lib && ln -s ../data/com.skia/lib com.skia-2)
-    
     echo "Copying symbol files"
-    $ADB pull /system/bin/skia_launcher $TMP_SYS_BIN
-    $ADB pull /system/lib/libc.so $TMP_SYS_LIB
-    $ADB pull /system/lib/libstlport.so $TMP_SYS_LIB
-    $ADB pull /system/lib/libcutils.so $TMP_SYS_LIB
-    $ADB pull /system/lib/libGLESv2.so $TMP_SYS_LIB
-    $ADB pull /system/lib/libandroid.so $TMP_SYS_LIB
-    $ADB pull /system/lib/libm.so $TMP_SYS_LIB
-    $ADB pull /system/lib/libz.so $TMP_SYS_LIB
-    
-    if [ $# -ge 2 ]
-    then
-        APP_NAME=$(basename $2)
-        $ADB pull /data/data/com.skia/lib/lib${APP_NAME}.so $TMP_APP_LIB
-    else 
-        $ADB pull /data/data/com.skia/lib/ $TMP_APP_LIB
-    fi
-    
+    adb_pull_if_needed /system/lib/libc.so $TMP_SYS_LIB
+    adb_pull_if_needed /system/lib/libstlport.so $TMP_SYS_LIB
+    adb_pull_if_needed /system/lib/libcutils.so $TMP_SYS_LIB
+    adb_pull_if_needed /system/lib/libGLESv2.so $TMP_SYS_LIB
+    adb_pull_if_needed /system/lib/libandroid.so $TMP_SYS_LIB
+    adb_pull_if_needed /system/lib/libm.so $TMP_SYS_LIB
+    adb_pull_if_needed /system/lib/libz.so $TMP_SYS_LIB
 
+    if [ ! -f "${SKIA_OUT}/${configuration}/lib.target/lib${runVars[0]}.so" ];
+    then
+      echo "Unable to find the ${runVars[0]} library"
+      exit 1
+    fi
+
+    echo "Pushing app..."
+    adb_push_if_needed "${SKIA_OUT}/${configuration}/skia_launcher" /data/local/tmp
+    adb_push_if_needed "${SKIA_OUT}/${configuration}/lib.target/libskia_android.so" /data/local/tmp
+    adb_push_if_needed "${SKIA_OUT}/${configuration}/lib.target/lib${runVars[0]}.so" /data/local/tmp
+
+    cp "${SKIA_OUT}/${configuration}/skia_launcher" $TMP_APP_LOC
+    cp "${SKIA_OUT}/${configuration}/lib.target/libskia_android.so" $TMP_APP_LOC
+    cp "${SKIA_OUT}/${configuration}/lib.target/lib${runVars[0]}.so" $TMP_APP_LOC
 }
 
 perf_record() {
 
-    APP_NAME=$(basename $2)
-    # Collect extra arguments to be passed to the skia_launcher binary
-    shift # perf_cmd
-    shift # app_name
-    while (( "$#" )); do
-      APP_ARGS="$APP_ARGS $1"
-      shift
-    done
-
-    echo "Checking for skia_launcher app..."
-    if [ ! -f $TMP_SYS_BIN/skia_launcher ]
-    then
-        echo "Unable to find the skia_launcher on the device"
-        rm -rf $PERF_TMP_DIR
-        exit 1;
-    fi
-    
-    echo "Checking for $APP_NAME library..."
-    if [ ! -f $TMP_APP_LIB/lib$APP_NAME.so ]
-    then
-        echo "Unable to find the app's shared library on the device"
-        rm -rf $PERF_TMP_DIR
-        exit 1;
-    fi
-    
     echo "Killing any running Skia processes."
     $ADB shell ps | grep skia_launcher | awk '{print $2}' | xargs $ADB shell kill
 
     echo "Starting application"
-    $ADB shell skia_launcher $APP_NAME $APP_ARGS &
+    $ADB shell /data/local/tmp/skia_launcher ${runVars[@]} &
 
     # WE REALLY REALLY WANT TO BE ABLE TO PASS THE SKIA_LAUNCHER APP DIRECTLY TO
     # PERF, BUT AT THIS POINT THE DATA FILE WE GET WHEN GOING THAT ROUTE IS UNABLE
@@ -107,13 +99,8 @@ perf_record() {
 }
 
 perf_report() {
-    # Collect extra arguments to be passed to the perfhost binary
-    while (( "$#" )); do
-      APP_ARGS="$APP_ARGS $1"
-      shift
-    done
-    
-    $PERFHOST report -i $PERF_TMP_DIR/perf.data --symfs=$PERF_TMP_DIR $APP_ARGS
+    adb_pull_if_needed /data/perf.data $PERF_TMP_DIR/perf.data
+    $PERFHOST report -i $PERF_TMP_DIR/perf.data --symfs=$PERF_TMP_DIR ${runVars[@]}
 }
 
 # Clean up
@@ -123,11 +110,11 @@ perf_clean() {
 
 case $PERF_CMD in
   setup)
-      perf_setup $@
+      perf_setup ${runVars[@]}
       ;;
   record)
-      perf_setup $@
-      perf_record $@
+      perf_setup ${runVars[@]}
+      perf_record ${runVars[@]}
       ;;
   report)
       perf_report
